### ISSUE TITLE
Some project development proposals

### ISSUE THREAD

**Issue by wojcik13** [truongan/wecode-judge#4]
Hello,
As You said in issue of mjnaderi's Sharif-Judge, You will try to implement some important suggestions and ideas, that can make this repo better one. Well, I have some ideas as following:

- IMO Sharif Judge should have ability to freeze scoreboard, as it is in other OJ's (DOMJudge). Usually in contest organized in Poland, it's enabled in half of contest time.
- As far as I'm concerned, Sharif should have better developed permissions system. I mean, to make some groups of students, so student from group A, cannot see contest assigned to group B, and vice versa. (My idea is to add students categories, and in <code>assignment_edit</code> view change participants box to <code>Categories of students allowed to see contest</code>)
- What do You think about adding switch, which is changing judging-method? One method is already programmed by mjnaderi, and the second method is ICPC-based
- Last suggestion is to precisely set publishing contests, so at setted time contest become visible, and deactivation time, so contest become invisible.

I'm curious, what is Your opinion about my proposals.

Kindly regards
Wojtek Wasilewski

P.S. Sorry for my poor english c:

**Comment by truongan** [comment]
Hi @wojcik13 
Thank you for your suggestion. But first and foremost I must say that my vision for wecode-judge (and sharif judge) is a classroom necessity only. If you need contest holding judge then DOM-Judge or the mordern https://cms-dev.github.io/ is much more suitable.

I agree with you that student should not be able to see assignment that are not available to them. But the Judge currently have the option to limit assignment for a list of students only, and I find that specify a list is convenient enough.

I already implement ICPC-base judging method. You can see it when choosing scoreboard and click on "minimal information", submission that does not pass ALL test case will be score as zero. 

I don't understand your last suggestion about assignment publish time. Just set the assignment start time and it will only be access at that time, what else to implement?
