### ISSUE TITLE
File not found during pending

### ISSUE THREAD

**Issue by rurunuela** [truongan/wecode-judge#7]
HI all seems to be correct but during submission pending stay actif and I have file not found on log and pending 
Any way to track the problem ? I try use directly run_docker and that work 
Thanks

**Comment by truongan** [comment]
It's seem that the queue processor faild to run. You have to put the file run_judge_in_docker.sh in your $PATH folders (in most case /usr/bin) and make sure the user that run webserver also have permission to run `sudo`

To get more details error message, you can try the following steps:

1. In the website, go to the top right corner, open menu Tools -> Submission Queue.
2. Pause the queue. 
3. In terminal, navigate the folder where you put index.php file and run following command:
```
export SHJ_BASE_URL='**https://your.base.ur/**'
php index.php queueprocess run 
```
Make sure that you those command as the same user that have run the webserver, and the part **https://your.base.ur/** is replaced with your real base url and properly escaped to pass as shell argument
You will get more detail error message on your terminal screen.

**Comment by rurunuela** [comment]
thanks
I change the php version  from 7 to 5.6 and all works ;-(

**Comment by truongan** [comment]
I guess it's a close issues then.
