### ISSUE TITLE
Could you add some functions in Wecode? 

### ISSUE THREAD

**Issue by nguyenthingocdiem** [truongan/wecode-judge#8]
While using Wecode, I see it will be more convenient if having some more functions:
1. Add a **Total Score cell** to sum all score of problems and a **Number column** of problems at 2 positions:
+ When admin creates an Assignment.
+ When students do an Assignment.
2. Add a checklist for completed problems in an Assignment. Similar to the Scoreboard for admin, students are limited to view only their work status.

Thanks.

**Comment by truongan** [comment]
Reasonable request. 
I add a small text with total score and number of problems when adding assignment and view problem of an assignment.
Also when viewing problem of an assignment, I highlight the score column of the problem list with proper status colors.
Close with  commit a880ba7
